### ISSUE TITLE
What is expected blocking behavior with blpop?

### ISSUE THREAD

**Issue by nsheard** [vert-x/mod-redis#27]
I'm having trouble with blpop blocking redis access in other verticles in the same Vertx instance and am wondering whether this is not supported or is as expected?

The exact scenario is that I have a verticle that deploys several other verticles including a worker verticle.  The worker verticle is reading a queue using blpop.  Whilst it is blocked all other calls to redis in other verticles timeout.  This is in mod redis 1.1.4 & vertx 2.1.4.

I've tried a few other code combinations but so far have not found a way around it.  If this is not expected behavior I can see if I can produce a simple test case.  I can work around the issue by using lpop although this is not ideal and so any advice would be greatly appreciated.

**Comment by minus7** [comment]
This is a Redis limitation actually. While the BLPOP command is waiting, the connection is not usable for other commands. The only way around this I know is to open a separate connection for BLPOP.

**Comment by nsheard** [comment]
Thanks, I will try it with a dedicated connection just for the BLPOP I need to do.

Ignoring BLPOP for a moment, I assume that other Redis commands can run asynchronously and concurrently in the same single deployed mod_redis?  i,e, internally in mod_redis they don't all get queued on the same connection?  I'm trying to work out if using mod-redis there is anything special I need to do to get the maximum thoughput of Redis commands.
