### ISSUE TITLE
Does vert-x3/vertx-redis-client replace mod-redis?

### ISSUE THREAD

**Issue by alanma** [vert-x/mod-redis#33]
Looks like mod-redis is not being actively worked on. So going forward, we should all use the new redis client built in vertx 3? Please confirm. Thanks.

**Comment by purplefox** [comment]
Vert.x 3 does not have a module system therefore mod-redis is Vert.x 2 only.

**Comment by pmlopes** [comment]
I will close this issue since i think it is clear:

if you use vert.x2, then this is the module you need
If you use vert.x3 the use vertx-redis-client
