### ISSUE TITLE
Extraction of handlers based on patterns

### ISSUE THREAD

**Issue by smiklosovic** [vert-x/mod-redis#34]
@purplefox @pmlopes 

Hi,

while I was looking for redis module for vert.x, I found this one and I am definitely going to try it.

I was looking into the code and the concept of the handlers which are registered against pattern-like addresses (as I understand it) is very sound to me and I would like to use this feature in different context from this module.

Basically I am more or less forced to use vert.x 2.x stream and I am looking for a way how to register a handler which accepts messages which are sent to address of some pattern and as far as I know there is not such functionality in vert.x 2.x (not sure about vert.x 3).

Do you think it would be possible to reuse your code or be inspired by it and code just API which envelops this functionality and can be reused as standard Maven / Gradle artifact?

Is there any existing way how to register pattern-like handler in vert.x 2.x at this moment?

Thanks

**Comment by pmlopes** [comment]
The patterns are a concept from redis:

http://redis.io/commands/psubscribe

But what you are asking is not related to this module but to vert.x 2 and I am afraid that you don't have that out of the box:

http://vertx.io/vertx2/api/java/index.html

**Comment by pmlopes** [comment]
I will close this issue since it is not related to redis but to vert.x2, if you really would like such a feature please open the issue on vert.x2 or contribute a pull request.
