### ISSUE TITLE
Getting rid of Groovy dependency

### ISSUE THREAD

**Issue by smiklosovic** [vert-x/mod-redis#35]
@pmlopes @purplefox 

Hi,

I want to use this module in my project which will be delivered as a fat jar hence, as I understand it right, once this module is added into mod.json and once fat jar is about to be created, fat jar will contain also all Groovy dependencies and it makes that jar  unnecessarily bloated.

Is there any motivation to strip down all Groovy features (removing all code and marks of Groovy) hence I can just bundle pure Java module into the fat jar?

I am ok with putting it into the branch (not master) and it can be released separately.

If there is not any will to do so, I think you will be forked and I just do it on my own anyway but I do not want to split the effort.

Thoughts?

**Comment by smiklosovic** [comment]
Huh, I looked into mod.json and there is not any sign of Groovy dependency which would be pulled into the fat jar so I believe that I am safe to bundle it and it will be just about Java.

I has a similar issue with some postgresql vert.x module which would pull into fat jar whole Scala runtime so I was thinking this is the same case.

Could somebody confirm this please so it can be closed?

Thanks a lot

**Comment by pmlopes** [comment]
Hi there, in the mod itself I think the scope of groovy is wrong it should be test, since tests were written in groovy, once that is done you should have a Java only module.

**Comment by smiklosovic** [comment]
This is what is bundled into the fat jar as of now. I do not know what you mean by test scope, all groovy dependencies are "provided".

As this is not something which would make fat jar significantly larger, I can live with these unrelated couple of classes and resources however I am curious how they even got there anyway.

```
[smikloso@localhost io.vertx~mod-redis-client~1.1.4]$ tree
.
|-- abstractRedisClient.js
|-- io
|   `-- vertx
|       |-- groovy
|       |   `-- redis
|       |       |-- AbstractRedisClient$1.class
|       |       |-- AbstractRedisClient.class
|       |       |-- AbstractRedisClient$_send_closure1.class
|       |       `-- RedisClient.class
|       `-- java
|           `-- redis
|               |-- AbstractRedisClient$1.class
|               |-- AbstractRedisClient.class
|               `-- RedisClient.class
|-- mod.json
|-- mods
|   `-- io.vertx~mod-redis~1.1.4
|       |-- io
|       |   `-- vertx
|       |       `-- redis
|       |           |-- Command.class
|       |           |-- impl
|       |           |   |-- MessageHandler.class
|       |           |   |-- RedisAsyncResult.class
|       |           |   |-- RedisSubscriptions.class
|       |           |   `-- ReplyHandler.class
|       |           |-- RedisConnection$1.class
|       |           |-- RedisConnection$2.class
|       |           |-- RedisConnection$3$1.class
|       |           |-- RedisConnection$3.class
|       |           |-- RedisConnection$4$1.class
|       |           |-- RedisConnection$4$2.class
|       |           |-- RedisConnection$4$3.class
|       |           |-- RedisConnection$4.class
|       |           |-- RedisConnection$5.class
|       |           |-- RedisConnection$6.class
|       |           |-- RedisConnection.class
|       |           |-- RedisConnection$State.class
|       |           |-- RedisMod$1.class
|       |           |-- RedisMod$2.class
|       |           |-- RedisMod$3.class
|       |           |-- RedisMod.class
|       |           |-- RedisMod$ResponseTransform.class
|       |           |-- Reply.class
|       |           `-- ReplyParser.class
|       `-- mod.json
`-- redisClient.js

12 directories, 35 files
```

**Comment by pmlopes** [comment]
the module does not include groovy dependency, however if you use the helper client then you will always get the groovy wrapper and javascript wrapper since it is how we bundle the polyglot api for vert.x2
