### ISSUE TITLE
setex command support

### ISSUE THREAD

**Issue by nitinagr** [vert-x/mod-redis#37]
Hi i want to use setex command in vertx with your module can you please let me if it supports and if yes than how can i call?

**Comment by pmlopes** [comment]
see here:
https://github.com/vert-x/mod-redis/blob/master/mod/src/test/groovy/io/vertx/redis/GRedisClientTester.groovy#L1494

If you're using the client:

https://github.com/vert-x/mod-redis/blob/master/mod-client/src/main/java/io/vertx/java/redis/RedisClient.java#L279
